<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'B13\\Container\\' => array($typo3InstallDir . 'typo3conf/ext/container/Classes'),
    'Causal\\Cloudflare\\' => array($typo3InstallDir . 'typo3conf/ext/cloudflare/Classes'),
    'Faf\\FafCompanies\\' => array($typo3InstallDir . 'typo3conf/ext/faf_companies/Classes'),
    'FluidTYPO3\\Vhs\\' => array($typo3InstallDir . 'typo3conf/ext/vhs/Classes'),
    'GeorgRinger\\News\\' => array($typo3InstallDir . 'typo3conf/ext/news/Classes'),
    'SFC\\Staticfilecache\\' => array($typo3InstallDir . 'typo3conf/ext/staticfilecache/Classes'),
    'T3G\\AgencyPack\\Blog\\' => array($typo3InstallDir . 'typo3conf/ext/blog/Classes'),
);
